version: '3'

services:
  # Nginx service 1
  nginx1:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./site1:/var/www/site1
      - ./nginx/site1.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php1
    networks:
      - laravel_network

  # Nginx 2
  nginx2:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./site2:/var/www/site2
      - ./nginx/site2.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php2
    networks:
      - laravel_network

  #PHP service 1 with Laravel
  php1:
    build:
      context: ./site1
      dockerfile: Dockerfile
    volumes:
      - ./site1:/var/www/site1
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=laravel
    depends_on:
      - mysql
    networks:
      - laravel_network

  #PHP service 2 with Laravel
  php2:
    build:
      context: ./site2
      dockerfile: Dockerfile
    volumes:
      - ./site2:/var/www/site2
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=laravel
    depends_on:
      - mysql
    networks:
      - laravel_network
  
  #MYSQL service
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    networks:
      - laravel_network
    ports:
      - "3306:3306"
    
networks:
  laravel_network:
      driver: bridge
